/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Heading: typeof import('./src/components/content-placeholder/Heading.vue')['default']
    Img: typeof import('./src/components/content-placeholder/Img.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShipPlaceholder: typeof import('./src/components/views/ShipPlaceholder.vue')['default']
    Text: typeof import('./src/components/content-placeholder/Text.vue')['default']
    Wrapper: typeof import('./src/components/content-placeholder/Wrapper.vue')['default']
  }
}
